site_name: Kamodo Core Analysis Suite

theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: blue

use_directory_urls: False

plugins:
  - search
  - include-markdown
  - mkdocs-jupyter:
      include_source: True
      kernel_name: python3
      execute: False
      ignore_h1_titles: True
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.superfences

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: README.md
  - About: about.md
  - Introduction: notebooks/Kamodo.ipynb
  - Visualization: notebooks/Visualization.ipynb
  - Syntax: notebooks/Syntax.ipynb
  - Kamodofying Models: notebooks/Kamodofying_Models.ipynb
  - Field Integration: notebooks/FieldIntegration.ipynb
  - Contributing: CONTRIBUTING.md
  - Additional Resources: additional_resources.md

