[metadata]
name = kamodo
version = 26.08.4
author = Darren De Zeeuw
author_email = darren.dezeeuw@nasa.gov
description = A functional api for scientific data
url = https://github.com/nasa/Kamodo-core
license_file = LICENSE
long_description = file: README.md
long_description_content_type = text/markdown
classifiers =
  Programming Language :: Python :: 3.10
  Programming Language :: Python :: 3.11
  Programming Language :: Python :: 3.12
  Programming Language :: Python :: 3.13
  Programming Language :: Python :: 3.14
	Operating System :: OS Independent
	License :: OSI Approved
license = NASA OPEN SOURCE AGREEMENT VERSION 1.3

[options]
packages = kamodo
python_requires = >= 3.10
include_package_data = True
install_requires =
  decorator>=4.4.2
  numpy
  scipy
  sympy
  antlr4-python3-runtime>=4.11,<4.12
  pandas
  plotly
  kaleido
  pytest
  pytest-cov
  Flask>=3.0.0
  flask-cors>=4.0.0
  flask-restful>=0.3.10
  python-forge
  requests
  pyYAML

[options.entry_points]
console_scripts =
    kamodo = kamodo.cli.main:entry
    kamodo-gui = kamodo.cli.gui:entry
    kamodo-serve = kamodo.cli.api:main
    kamodo-rpc = kamodo.cli.rpc:entry
    gen-self-signed-cert = kamodo.rpc.gen_self_signed_cert:entry
    
